version: '3'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri file:/mlflow/mlruns
      --default-artifact-root file:/mlflow/mlruns